name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  yd-bal:
    name: Archive YD-Bal
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: yd_bal
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: zip -Z deflate ieee4-yd_bal.ckt *.csv *.json README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: ckt-yd-bal
          path: ieee4-yd_bal.ckt
  dy-bal:
    name: Archive DY-Bal
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dy_bal
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: zip -Z deflate ieee4-dy_bal.ckt *.csv *.json README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: ckt-dy-bal
          path: ieee4-dy_bal.ckt

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions: write-all
    needs: [ yd-bal, dy-bal ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ckt-yd-bal
      - uses: actions/download-artifact@v2
        with:
          name: ckt-dy-bal

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload YD-Bal artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ieee4-yd_bal.ckt
          asset_name: ieee4-yd_bal
          asset_content_type: application/zip

      - name: Upload DY-Bal artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ieee4-dy_bal.ckt
          asset_name: ieee4-dy_bal
          asset_content_type: application/zip